# 端口与日志
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      request-attributes-enabled: true
      directory: logs
      pattern: commonopen



# 应用信息
spring:
  application:
    name: spring-cloud-eureka




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka


