server:
  port: 8070
  tomcat:
    uri-encoding: UTF-8

service-url:
  user-service: http://localhost:8085


spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: ${service-url.user-service}/user/getByUsername{name}
          predicates:
            - Path=/user/getByUsername

