server:
  port: 8075

spring:
  application:
    name: spring-cloud-admin-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka