# 端口与日志
server:
  port: 8061
  tomcat:
    uri-encoding: UTF-8



# 应用信息
spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      label: master
      profile: dev
      #  配置文件名称
      name: application
      uri: http://localhost:8060



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka

management:
  endpoint:
    web:
      exposure:
        include: '*'
