# 端口与日志
server:
  port: 8066
  tomcat:
    uri-encoding: UTF-8




# 应用信息
spring:
  application:
    name: spring-cloud-consul-ribbon
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}




service-url:
  book-service: http://spring-cloud-consul-book-service

