# 端口与日志
server:
  port: 8092
  tomcat:
    uri-encoding: UTF-8




# 应用信息
spring:
  application:
    name: spring-cloud-ribbon
  zipkin:
    # 该地址为zipkin-server的地址，zipkin需要另外下载
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 设置zipkin抽样收集概率
      probability: 1



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka


service-url:
  ribbon-provider-service: http://spring-cloud-ribbon-provider